[tool.poetry]
name = "darkweb"
version = "0.1.0"
description = ""
authors = ["jo06 <jo06@jo06.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
selenium = "^4.27.1"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
